version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewGitprojectTestProject
  gitServerName: SanthoshKToken7D
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.newgitprojecttest.integrations:Testnew
  packages:
  - name: NewGitprojectTestProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.1126
